image: trion/ng-cli-karma

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 --decode)
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    
stages:
  - test
  - deploy    

test: 
  image: node:9-alpine
  script:
    - cd backend
    - npm i
    - npm test

deploy:
  type: deploy
  environment:
    name: production
    url: dedibox.ghyslain.xyz
  script:
    - ssh ghys@dedibox.ghyslain.xyz "cd lazyker && git pull && ./deploy.sh"
  only:
    - dedibox