before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
#  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 --decode)
#  - Odroid part
#  - private key must be b64 encoded https://www.base64encode.org/ and include "---begin rsa"... and "--- end rsa..."
#  - new way of doing such a thing : https://docs.gitlab.com/ee/ci/ssh_keys/ --> copy/paste full id_rsa private key (with "begin" and "end" characters, and not b64 encode it
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - pull
  - test
  - analysis
  - deploy

pull_changes:
  stage: pull
  environment:
    name: production
    url: lazyker.ghyslain.xyz
  script:
    - ssh ghyslain@ghyslain.xyz "cd lazyker && git reset --hard && git clean -f && git pull"
  only:
    - nuc

test_backend:
  stage: test
  environment:
    name: production
    url: lazyker.ghyslain.xyz
  script:
    - ssh ghyslain@ghyslain.xyz "cd lazyker && ./deploy.sh test_backend"
  only:
    - nuc

backend_analysis:
  stage: analysis
  environment:
    name: production
    url: lazyker.ghyslain.xyz
  script:
    - ssh ghyslain@ghyslain.xyz "cd lazyker && ./deploy.sh backend_analysis"
  only:
    - nuc

frontend_analysis:
  stage: analysis
  environment:
    name: production
    url: lazyker.ghyslain.xyz
  script:
    - ssh ghyslain@ghyslain.xyz "cd lazyker && ./deploy.sh frontend_analysis"
  only:
    - nuc

deploy_nuc:
  stage: deploy
  environment:
    name: production
    url: lazyker.ghyslain.xyz
  script:
    - ssh ghyslain@ghyslain.xyz "cd lazyker && ./deploy.sh docker"
  only:
    - nuc
