before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
#  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 --decode)
#  - Odroid part
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 --decode)
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - deploy

deploy_dedibox:
  stage: deploy
  environment:
    name: production
    url: dedibox.ghyslain.xyz
  script:
    - ssh ghys@dedibox.ghyslain.xyz "cd lazyker && git pull && ./deploy.sh"
  only:
    - dedibox

deploy_odroid:
  stage: deploy
  environment:
    name: production
    url: dedibox.ghyslain.xyz
  script:
    - ssh pi@dedibox.ghyslain.xyz "cd lazyker && git pull && ./deploy.sh"
  only:
    - architecture-arm